# Generated by Django 5.1.15 on 2026-03-17 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='best_seller',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Mais vendida'),
        ),
        migrations.AlterField(
            model_name='product',
            name='featured',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Destaque'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Ativo'),
        ),
    ]
