export const PRODUCTS = [
  {
    id: 1,
    name: "Vou Mimi",
    slug: "vou-mimi",
    phrase: "Vou mimi, amanha tem muito rojao.",
    description: "Caneca preta com frase divertida em branco. Perfeita pra quem ama dormir e tem muito o que fazer no dia seguinte.",
    price: 39.90,
    originalPrice: 49.90,
    category: "humor",
    images: ["/images/products/vou-mimi.jpg"],
    featured: true,
    bestSeller: true,
    colors: ["Preta"],
    material: "Ceramica 325ml",
  },
  {
    id: 2,
    name: "So Faco Café",
    slug: "so-faco-cafe",
    phrase: "Ja fiz muita questão, hoje so faco café.",
    description: "Caneca branca em tons de marrom, com um personagem fofo. Para quem ja cansou de fazer questão e agora so quer um bom café.",
    price: 39.90,
    category: "cafe",
    images: ["/images/products/so-faco-cafe.jpg"],
    featured: true,
    bestSeller: false,
    colors: ["Branca"],
    material: "Ceramica 325ml",
  },
  {
    id: 3,
    name: "Te Amo Pra Sempre",
    slug: "te-amo-pra-sempre",
    phrase: "Te amo pra sempre com voce.",
    description: "Caneca romantica com coracoes e rosas. Presente perfeito para o dia dos namorados ou qualquer dia especial.",
    price: 44.90,
    category: "romanticas",
    images: ["/images/products/te-amo.jpg"],
    featured: true,
    bestSeller: false,
    colors: ["Branca"],
    material: "Ceramica 325ml",
  },
  {
    id: 4,
    name: "Troco Gente Chata",
    slug: "troco-gente-chata",
    phrase: "Troco gente chata por café!",
    description: "Caneca rosa e branca pra quem prefere a companhia de um bom café. Estilo floral divertido.",
    price: 39.90,
    category: "humor",
    images: ["/images/products/troco-gente.jpg"],
    featured: true,
    bestSeller: true,
    colors: ["Rosa/Branca"],
    material: "Ceramica 325ml",
  },
  {
    id: 5,
    name: "Rock n Roll",
    slug: "rock-n-roll",
    phrase: "Rock'n'Roll",
    description: "Caneca branca com caveiras e notas musicais. Para os amantes do rock que curtem um café com atitude.",
    price: 39.90,
    category: "musica",
    images: ["/images/products/rock-n-roll.jpg"],
    featured: false,
    bestSeller: false,
    colors: ["Branca"],
    material: "Ceramica 325ml",
  },
  {
    id: 6,
    name: "O Som da Minha Vida",
    slug: "som-da-minha-vida",
    phrase: "O som da minha vida",
    description: "Caneca com design musical em preto e vermelho. Para quem vive com uma trilha sonora tocando.",
    price: 39.90,
    category: "musica",
    images: ["/images/products/som-vida.jpg"],
    featured: true,
    bestSeller: false,
    colors: ["Branca"],
    material: "Ceramica 325ml",
  },
  {
    id: 7,
    name: "Caneca Personalizada",
    slug: "caneca-personalizada",
    phrase: "Sua frase aqui!",
    description: "Monte a caneca do seu jeito! Escolha a frase, o estilo e as cores. Nos fazemos pra voce com todo carinho.",
    price: 49.90,
    category: "personalizadas",
    images: ["/images/products/personalizada.jpg"],
    featured: true,
    bestSeller: true,
    colors: ["Branca", "Preta"],
    material: "Ceramica 325ml",
  },
  {
    id: 8,
    name: "Modo Cafe ON",
    slug: "modo-cafe-on",
    phrase: "Modo cafe: ON",
    description: "Caneca pra quem já acorda pensando no primeiro café do dia. Design minimalista e direto ao ponto.",
    price: 39.90,
    category: "cafe",
    images: ["/images/products/modo-cafe.jpg"],
    featured: false,
    bestSeller: false,
    colors: ["Branca"],
    material: "Ceramica 325ml",
  },
]
